version: 2
jobs:
  build:
    working_directory: ~/nodechain
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: npm-install-module
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: npm-test
          command: npm run test